name: Build and Release Oblysk

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.5.0)'
        required: true
        default: 'v1.5.0'

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create tray icon if missing
        run: |
          if (!(Test-Path "tray-icon.png")) {
            if (Test-Path "OGOBLYSK.png") {
              Copy-Item "OGOBLYSK.png" "tray-icon.png"
              Write-Host "✅ Created tray-icon.png from OGOBLYSK.png"
            } elseif (Test-Path "icon.ico") {
              Write-Host "⚠️ Using icon.ico as fallback for tray-icon.png"
              # Note: Would need conversion tool for .ico to .png
            } else {
              Write-Host "❌ Warning: No tray icon found"
              # Create a simple placeholder
              echo "Placeholder tray icon needed" > tray-icon.png
            }
          } else {
            Write-Host "✅ tray-icon.png already exists"
          }
        shell: powershell
      
      - name: Build Windows executables
        run: npm run build-all
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: List build artifacts
        run: |
          Write-Host "🔍 Build artifacts created:"
          if (Test-Path "dist") {
            Get-ChildItem dist -Recurse -Name | ForEach-Object {
              $file = Get-Item "dist/$_"
              $size = [math]::Round($file.Length / 1MB, 2)
              Write-Host "  📄 $_ (${size} MB)"
            }
          } else {
            Write-Host "❌ No dist folder found!"
            exit 1
          }
        shell: powershell
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: oblysk-windows-build
          path: |
            dist/*.exe
            dist/*.blockmap
          retention-days: 30
      
      - name: Generate checksums
        run: |
          cd dist
          Write-Host "🔐 Generating checksums..."
          Get-ChildItem *.exe | ForEach-Object {
            $hash = Get-FileHash $_.Name -Algorithm SHA256
            $checksum = "$($hash.Hash.ToLower())  $($_.Name)"
            Write-Host "  $checksum"
            $checksum | Out-File -Append "checksums.txt" -Encoding ASCII
          }
          
          if (Test-Path "checksums.txt") {
            Write-Host "✅ Checksums file created:"
            Get-Content "checksums.txt"
          }
        shell: powershell
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/checksums.txt
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## 🚀 Oblysk ${{ github.ref_name }}
            
            **Enterprise-grade console paste tool for Windows virtual consoles**
            
            ### 📦 Downloads
            
            | File | Description | Size |
            |------|-------------|------|
            | **Oblysk-Portable-Windows.exe** | 🎯 **Recommended** - Portable version, no installation needed | ~50MB |
            | **Oblysk-${{ github.ref_name }}-Windows-x64.exe** | 📦 Installer for 64-bit Windows | ~50MB |
            | **Oblysk-${{ github.ref_name }}-Windows-arm64.exe** | 📦 Installer for ARM64 Windows | ~50MB |
            | **checksums.txt** | 🔐 SHA256 checksums for verification | 1KB |
            
            ### ⚡ Quick Start
            1. **Download** `Oblysk-Portable-Windows.exe` 
            2. **Run** the executable (no installation needed)
            3. **Setup** your master password when prompted
            4. **Store** commands/passwords in grid cells (double-click)
            5. **Paste anywhere** with `Ctrl+Alt+1-9`
            
            ### 🎯 Perfect For
            - 🖥️ **VMware vSphere/ESXi** consoles
            - ☁️ **AWS CloudShell** and web terminals  
            - 🔧 **iDRAC/iLO/IPMI** interfaces
            - 🏢 **Corporate VDI** environments
            - 🐧 **SSH terminals** and command prompts
            
            ### 🔒 Security Note
            Windows Defender may show a warning for new executables. This is normal - you can:
            - ✅ Click "More info" → "Run anyway" 
            - ✅ Verify the SHA256 checksum matches `checksums.txt`
            - ✅ Check the source code at https://github.com/AnarchySC/oblysk
            
            ### 🐛 Found an Issue?
            - 📋 **Report bugs**: [Create an issue](https://github.com/AnarchySC/oblysk/issues/new/choose)
            - 💬 **Get help**: [Join discussions](https://github.com/AnarchySC/oblysk/discussions)
            - 🔧 **Debug info**: Press `Ctrl+Shift+D` in the app to export logs
            
            **Full changelog**: https://github.com/AnarchySC/oblysk/releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update latest release info
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          Write-Host "🎉 Release ${{ github.ref_name }} published successfully!"
          Write-Host "📍 Available at: https://github.com/AnarchySC/oblysk/releases/tag/${{ github.ref_name }}"
        shell: powershell

  notify-success:
    runs-on: ubuntu-latest
    needs: build-and-release
    if: success() && startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Release notification
        run: |
          echo "🎉 Oblysk ${{ github.ref_name }} has been successfully released!"
          echo "📦 Windows executables are now available for download"
          echo "🔗 Release URL: https://github.com/AnarchySC/oblysk/releases/tag/${{ github.ref_name }}"
